package com.example.pomodoro2.features.tasks.presentation

import android.os.Bundle
import android.view.*
import android.widget.Toast
import androidx.databinding.DataBindingUtil
import androidx.lifecycle.Observer
import androidx.lifecycle.ViewModelProvider
import androidx.navigation.findNavController
import androidx.navigation.ui.NavigationUI
import androidx.recyclerview.widget.GridLayoutManager
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.pomodoro2.R
import com.example.pomodoro2.framework.platform.BaseFragment
import com.example.pomodoro2.framework.platform.EventObserver
import com.example.pomodoro2.databinding.FragmentTaskBinding
import com.example.pomodoro2.domain.Task
import com.google.android.material.snackbar.Snackbar

class TaskFragment : BaseFragment() {

    private lateinit var tasksViewModel: TasksViewModel

    override fun layoutId(): Int {
        return R.layout.fragment_task
    }

    // Customize parameter argument names
    private val ARG_COLUMN_COUNT = "column-count"
    // Customize parameters for Grid LayoutManager of RecyclerView
    private var _columnCount = 1

    fun newInstance(columnCount: Int): TaskFragment? {
        val fragment = TaskFragment()
        val args = Bundle()
        args.putInt(ARG_COLUMN_COUNT, columnCount)
        with(fragment) {
            args.putInt(ARG_COLUMN_COUNT, columnCount)
            setArguments(args)
        }
        return fragment
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        if (arguments != null) {
            _columnCount = requireArguments().getInt(ARG_COLUMN_COUNT)
        }
    }

    /**
     * Called when the Fragment is ready to display content to the screen.
     *
     * This function uses DataBindingUtil to inflate R.layout.fragment_task.
     *
     * It is also responsible for passing the [TasksViewModel] to the
     * [FragmentProjectBinding] generated by DataBinding. This will allow DataBinding
     * to use the LiveData on our ViewModel.
     */
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {

        // Get a reference to the binding object and inflate the fragment views.
        val binding: FragmentTaskBinding = DataBindingUtil.inflate(
            inflater, layoutId(), container, false
        )

        val application = requireNotNull(this.activity).application

        // Create an instance of the ViewModel Factory.
        val viewModelFactory = TasksViewModelFactory(application)

        // Get a reference to the ViewModel associated with this fragment.
        tasksViewModel =
            ViewModelProvider(this, viewModelFactory).get(TasksViewModel::class.java)

        // To use the View Model with data binding, you have to explicitly
        // give the binding object a reference to it.
        binding.viewModel = tasksViewModel

        // Specify the current activity as the lifecycle owner of the binding.
        // This is necessary so that the binding can observe LiveData updates.
        binding.lifecycleOwner = this


        // Set RecycleView.layoutManager
        if (_columnCount <= 1) {
            binding.projectList.layoutManager = LinearLayoutManager(activity)
        } else {
            val manager = GridLayoutManager(activity, _columnCount)
            manager.spanSizeLookup = object : GridLayoutManager.SpanSizeLookup() {
                override fun getSpanSize(position: Int) =  when (position) {
                    0 -> _columnCount
                    else -> 1
                }
            }
            binding.projectList.layoutManager = manager

        }

        // Set RecycleView.adapter
        val adapter = TaskRecyclerViewAdapter(TaskListener { task ->
            //Toast.makeText(context, "${project.id}", Toast.LENGTH_LONG).show()
            tasksViewModel.onTaskClicked(task)
        })
        binding.projectList.adapter = adapter


        tasksViewModel.tasks.observe(viewLifecycleOwner, Observer {
            it?.let {
                adapter.addHeaderAndSubmitList(it)
            }
        })

        // Add an Observer on the state variable for showing a SnackBar message
        tasksViewModel.showSnackBarEvent.observe(viewLifecycleOwner, EventObserver {
            Snackbar.make(
                requireActivity().findViewById(android.R.id.content),
                it,
                Snackbar.LENGTH_SHORT // How long to display the message.
            ).show()
        })

        // Add an Observer on the state variable for Navigating
        tasksViewModel.navigateToActivityFragment.observe(viewLifecycleOwner, EventObserver {
            requireView().findNavController().navigate(
                TaskFragmentDirections.actionNavigationProjectToNavigationActivity(it)
            )
        })

        setHasOptionsMenu(true)

        binding.fab.setOnClickListener{
            Toast.makeText(
                context, "You clicked fab button",
                Toast.LENGTH_SHORT
            ).show()
        }

        return binding.root
    }



    override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
        super.onCreateOptionsMenu(menu, inflater)
        inflater.inflate(R.menu.options_menu, menu)
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        return when (item.itemId) {
            R.id.action_create_data -> {
                Toast.makeText(
                    context, "Pseudo_Data created",
                    Toast.LENGTH_SHORT
                ).show()

                tasksViewModel.createTestData()
                true
            }

            R.id.action_delete_data -> {
                Toast.makeText(
                    context, "Pseudo_Data deleted",
                    Toast.LENGTH_SHORT
                ).show()
                tasksViewModel.clearTestData()
                true
            }

            R.id.aboutFragment -> {
                NavigationUI.onNavDestinationSelected(
                    item,
                    requireView().findNavController()
                )
            }

            R.id.action_snack_bar -> {
                tasksViewModel.testSnackBar()

                val project =
                    Task(
                        title = "学习Android开发",
                        imageId = R.drawable.read_book,
                        priority = 1
                    )
                tasksViewModel.doNavigating(project)
                true
            }

            else -> super.onOptionsItemSelected(item)
        }
    }
}