package com.example.pomodoro2.features.activities.presentation

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.databinding.DataBindingUtil
import androidx.lifecycle.Observer
import androidx.lifecycle.ViewModelProvider
import com.example.pomodoro2.R
import com.example.pomodoro2.framework.platform.BaseFragment
import com.example.pomodoro2.databinding.FragmentActivityBinding
import com.example.pomodoro2.features.infra.database.AppDatabase
import kotlinx.android.synthetic.main.fragment_activity.*

class ActivityFragment : BaseFragment() {

    private lateinit var activitiesViewModel: ActivitiesViewModel

    override fun layoutId(): Int {
        return R.layout.fragment_activity
    }

    /**
     * Called when the Fragment is ready to display content to the screen.
     *
     * This function uses DataBindingUtil to inflate R.layout.fragment_activity.
     *
     * It is also responsible for passing the [ActivitiesViewModel] to the
     * [FragmentActivityBinding] generated by DataBinding. This will allow DataBinding
     * to use the [LiveData] on our ViewModel.
     */
    override fun onCreateView(
            inflater: LayoutInflater,
            container: ViewGroup?,
            savedInstanceState: Bundle?
    ): View {

        // Get a reference to the binding object and inflate the fragment views.
        val binding: FragmentActivityBinding = DataBindingUtil.inflate(
            inflater, layoutId(), container, false)

        val application = requireNotNull(this.activity).application
        val arguments = ActivityFragmentArgs.fromBundle(requireArguments())

        // Create an instance of the ViewModel Factory.
        // TODO:change ProjectDAO to ActivityDAO later
        val dataSource = AppDatabase.getInstance(application).taskDao
        val viewModelFactory = ActivitiesViewModelFactory(arguments.task, dataSource)

        // Get a reference to the ViewModel associated with this fragment.
        val activitiesViewModel =
            ViewModelProvider(this, viewModelFactory).get(ActivitiesViewModel::class.java)

        // To use the View Model with data binding, you have to explicitly
        // give the binding object a reference to it.
        binding.viewModel = activitiesViewModel
        binding.lifecycleOwner = this

        // Add an Observer to the state variable for Navigating when a Quality icon is tapped.

        activitiesViewModel.text.observe(viewLifecycleOwner, Observer {
            text_activity.text = it
        })

        return binding.root
    }
}