package com.example.pomodoro2.features.activities.presentation

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.databinding.DataBindingUtil
import androidx.lifecycle.Observer
import androidx.lifecycle.ViewModelProvider
import com.example.pomodoro2.R
import com.example.pomodoro2.data.DataSourceContainer
import com.example.pomodoro2.data.DefaultTaskRepository
import com.example.pomodoro2.databinding.FragmentActivityBinding
import com.example.pomodoro2.features.activities.domain.ActivityInteractors
import com.example.pomodoro2.framework.base.BaseFragment
import dagger.hilt.android.AndroidEntryPoint
import kotlinx.android.synthetic.main.fragment_activity.*

@AndroidEntryPoint
class ActivityFragment : BaseFragment() {

    private lateinit var activitiesViewModel: ActivitiesViewModel

    override fun layoutId(): Int {
        return R.layout.fragment_activity
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        activitiesViewModel = buildViewModel()
    }

    private fun buildViewModel(): ActivitiesViewModel {
        // Build the ViewModelFactory with Interactors for this feature
        val application = requireNotNull(this.activity).application

        // TODO: change to activity repository
        val taskRepository = DefaultTaskRepository.getInstance(
            DataSourceContainer.remoteTaskDataSource,
            DataSourceContainer.roomTaskDataSource,
            DataSourceContainer.inMemoryDataSource
        )
        ActivitiesViewModelFactory.inject(
            application,
            ActivityInteractors(
                //TODO: Add use case set for activity feature here
            )
        )

        // Get a reference to the ViewModel associated with this fragment.
        return ViewModelProvider(requireActivity(), ActivitiesViewModelFactory)
            .get(ActivitiesViewModel::class.java)
    }

    /**
     * Called when the Fragment is ready to display content to the screen.
     *
     * This function uses DataBindingUtil to inflate R.layout.fragment_activity.
     *
     * It is also responsible for passing the [ActivitiesViewModel] to the
     * [FragmentActivityBinding] generated by DataBinding. This will allow DataBinding
     * to use the [LiveData] on our ViewModel.
     */
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {

        // Get a reference to the binding object and inflate the fragment views.
        val binding: FragmentActivityBinding = DataBindingUtil.inflate(
            inflater, layoutId(), container, false
        )

        val arguments = ActivityFragmentArgs.fromBundle(requireArguments())
        val currentTask = arguments.task
        //TODO: attach current task to view model

        // To use the View Model with data binding, you have to explicitly
        // give the binding object a reference to it.
        binding.viewModel = activitiesViewModel
        binding.lifecycleOwner = this

        // Add an Observer to the state variable for Navigating when a Quality icon is tapped.

        activitiesViewModel.text.observe(viewLifecycleOwner, Observer {
            text_activity.text = it
        })

        activitiesViewModel.setSelectedTask(currentTask)

        return binding.root
    }



}